apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: sanskarjoshi1148/todo-app:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000
        readinessProbe:
            tcpSocket:
                port: 8000
            initialDelaySeconds: 5
            periodSeconds : 10
        livenessProbe:
            tcpSocket:
                port: 8000
            initialDelaySeconds : 15
            periodSeconds: 20
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 1
            memory: 500Mi
