apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-ns

spec:

  selector:
    app: todo-app
  ports:
    - protocol: TCP
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8000
     
